"""
根据当前 SQLModel 元数据生成 PostgreSQL 初始化脚本（建表 + 默认管理员 + gitcc 供应商占位）。

用法（在 backend 目录下）:
  uv run python scripts/generate_init_sql.py

输出: 仓库根目录 database/postgresql/init.sql
修改模型后请重新运行本脚本以同步 DDL。
"""
from __future__ import annotations

import sys
from pathlib import Path

# backend 作为 cwd / path
BACKEND_ROOT = Path(__file__).resolve().parent.parent
REPO_ROOT = BACKEND_ROOT.parent
OUT_PATH = REPO_ROOT / "database" / "postgresql" / "init.sql"

# 默认管理员（README 与种子一致）；密码明文 admin@qq.com 的 bcrypt，勿改 rounds 除非同步更新 verify
DEFAULT_ADMIN_EMAIL = "admin@qq.com"
DEFAULT_ADMIN_PASSWORD_BCRYPT = (
    "$2b$12$jnCxOAyCvkC0/jmqascMsumbWtEEyU5AoArboyiqUsAavzxqEXPW6"
)
ADMIN_ACCOUNT_ID = "a0000001-0000-4000-8000-000000000001"
ADMIN_PROFILE_ID = "a0000002-0000-4000-8000-000000000001"
GITCC_PROVIDER_ID = "b0000001-0000-4000-8000-000000000001"


def main() -> None:
    sys.path.insert(0, str(BACKEND_ROOT))

    import app.src.model  # noqa: F401
    from app.src.model.model_config_models import (  # noqa: F401
        SystemModelDefinition,
        SystemModelProvider,
        UserModelPreference,
        UserProviderConfig,
    )
    from sqlmodel import SQLModel
    from sqlalchemy.schema import CreateTable
    from sqlalchemy.dialects import postgresql

    dialect = postgresql.dialect()

    parts: list[str] = [
        "-- zhongyi-agentic PostgreSQL init",
        "-- Generated by backend/scripts/generate_init_sql.py — do not edit DDL by hand",
        "BEGIN;",
        "",
    ]

    for table in SQLModel.metadata.sorted_tables:
        stmt = CreateTable(table).compile(dialect=dialect)
        parts.append(str(stmt).strip())
        parts.append(";")
        parts.append("")

    parts.append(
        f"""-- 默认管理员（登录 /login/admin：用户名填邮箱 {DEFAULT_ADMIN_EMAIL}，密码同邮箱）"""
    )
    parts.append(
        f"""INSERT INTO accounts (id, email, password_hash, account_type, is_active, created_at, updated_at)
SELECT '{ADMIN_ACCOUNT_ID}'::uuid, '{DEFAULT_ADMIN_EMAIL}', '{DEFAULT_ADMIN_PASSWORD_BCRYPT}', 'admin', true, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM accounts WHERE email = '{DEFAULT_ADMIN_EMAIL}' AND account_type = 'admin');"""
    )
    parts.append("")
    parts.append(
        f"""INSERT INTO admins (id, account_id, username, avatar_url, admin_level, permissions, created_at, updated_at)
SELECT '{ADMIN_PROFILE_ID}'::uuid, '{ADMIN_ACCOUNT_ID}'::uuid, 'admin', NULL, 'admin', '{{}}'::json, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM accounts WHERE id = '{ADMIN_ACCOUNT_ID}'::uuid)
  AND NOT EXISTS (SELECT 1 FROM admins WHERE account_id = '{ADMIN_ACCOUNT_ID}'::uuid);"""
    )
    parts.append("")
    parts.append("-- GitCC 聚合网关占位（与前端 FIXED_PUBLIC_PROVIDER_NAME 一致）")
    parts.append(
        f"""INSERT INTO system_model_providers (
    id, name, label, description, icon, icon_background, default_base_url,
    supported_model_types, help_url, position, owner_id, created_at, updated_at
)
SELECT '{GITCC_PROVIDER_ID}'::uuid,
       'gitcc',
       'GitCC API',
       'GitCC / New API 聚合网关（OpenAI 兼容）',
       NULL,
       '#FFFFFF',
       'http://api.gitcc.com/v1',
       '["llm","multimodal","embedding","image","audio","code","rerank"]'::json,
       'http://api.gitcc.com/',
       0,
       NULL,
       NOW(),
       NOW()
WHERE NOT EXISTS (SELECT 1 FROM system_model_providers WHERE LOWER(TRIM(name)) = 'gitcc');"""
    )
    parts.append("")
    parts.append("COMMIT;")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
